# Generated by Django 4.1.5 on 2023-04-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_training_training_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='training_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.training'),
        ),
    ]
