# Generated by Django 4.1.5 on 2023-04-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_produit_training_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='./field360App/media/'),
        ),
    ]
