# Generated by Django 4.1.5 on 2023-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chapters_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footsoldiers',
            name='footsoldiers_zone',
            field=models.CharField(max_length=100),
        ),
    ]
