# Generated by Django 4.1.5 on 2023-04-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_footsoldiers_footsoldiers_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footsoldiers',
            name='footsoldiers_clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clients'),
        ),
        migrations.AlterField(
            model_name='footsoldiers',
            name='footsoldiers_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
    ]
