# Generated by Django 4.1.5 on 2023-04-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_footsoldiers_footsoldiers_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footsoldiers',
            name='footsoldiers_clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients'),
        ),
    ]
