# Generated by Django 4.1.5 on 2023-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_footsoldiers_footsoldiers_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='photo_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='./field360App/media/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='piece_recto',
            field=models.ImageField(blank=True, null=True, upload_to='./field360App/media/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='piece_verso',
            field=models.ImageField(blank=True, null=True, upload_to='./field360App/media/'),
        ),
    ]
