# Generated by Django 4.1.5 on 2023-04-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_kyc_photo_selfie_alter_kyc_piece_recto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='country_kyc',
        ),
    ]
